config/routes.rb
Rails.application.routes.draw do

  root "welcome#home"

  # match 'auth/failure', to: redirect('/'), via: [:get, :post]
  get '/auth/facebook/callback' => 'sessions#create'

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  post "/logout", to: "sessions#destroy", as: '/logout'

  get '/signup' => 'users#new', as: 'signup'
  post '/signup' => 'users#create'
  get '/dashboard' => 'users#index', as: 'dashboard'

  post '/projects' => 'projects#create'

  resources :users
  resources :entries
  resources :projects

  resources :users, only: [:create, :show] do 
    resources :projects
  end

  resources :users, only: [:create] do 
    resources :entries
  end

  resources :project, only: [:show] do
    resources :entries, only: [:new, :create]
  end

  get '/status' => 'projects#status'
  get '/all-projects' => 'projects#allprojects'


end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/format_date.rb
module FormatDate
  extend ActiveSupport::Concern

  module InstanceMethods
   def calc_date(date)
    date.strftime("%b %d, %Y")
   end
  end

end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :project

  validates :notes, presence: true

  include FormatDate::InstanceMethods

  def self.desc_order
  	order(date: :desc)
  end

   def self.latest
   	desc_order.limit(3)
   end

   def calc_time(time)
  	time.strftime("%H:%M")    
   end

   def self.sort_by_project(project_id)
    where(project: project_id)
   end

   def self.calc_hours(entries)
     	time_array = []
     	entries.each do |entry|
     	  time_array << calc_hours_entry(entry)
      end
     	time_array.sum
   end

   def self.calc_hours_entry(entry)
    entry.hours_to_i(entry.end_time) - entry.hours_to_i(entry.start_time)
  end

   def hours_to_i(time)
    calc_time(time).slice(0,2).to_i
   end

end

app/models/project.rb
class Project < ApplicationRecord
  has_many :entries, :dependent => :destroy
  has_many :users, through: :entries

  validates :name, presence: true

  include FormatDate::InstanceMethods

  def statuses
  	[	"Just Started", 
  		"In Progress", 
  		"Almost Finished", 
  		"Complete", 
  		"Total Failure",
      "Losing Money"
  	]
  end

  def self.project_owner(project)
    User.find(project.owner)
  end

  def self.user_projects(user)
    where(owner: user)
  end

  def self.status(status)
    where(status: status)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :entries
  has_many :projects, through: :entries
  has_secure_password
  has_one_attached :image

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true 
  validates :password, presence: true
  validates :password_confirmation, presence: true

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  # validate :image_validated?

 #  def image_validated?
	# if image.attached? && !image.content_type.in?(%w(image/jpeg image/png))
	#   errors.add(:image, 'must be a JPEG or PNG format.')
	# elsif image.attached? == false
	#   errors.add(:image, 'must be included')
	# end
 #  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	before_action :current_user
	before_action :require_logged_in, except: [:new, :create, :home]

	def logged_in?
	   !!current_user
    end

    private
    def require_logged_in
      redirect_to root_path unless logged_in?
    end

	def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
      #was having issues with session properly clearing while testing
      rescue ActiveRecord::RecordNotFound 
      session[:user_id] = nil
    end

    helper_method :current_user
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

	def index
		@project = Project.all

######## JS code
		@entries = current_user.entries.desc_order
		@entry_hours = Entry.calc_hours(@entries)

		respond_to do |f|
			f.html {render :index}
			f.json {render json: @entries}
		end
	end 

	def new
		@entry = Entry.new
		#could be added as a view helper?
		if params[:project_id]
			@selected = Project.find(params[:project_id]).id
		else
			@selected = Project.first.id
		end
	end

	def create
		@entry = Entry.new(entry_params)
		if @entry.valid?
			@entry.save
			flash[:success] = "Time entry successfully saved."
			redirect_to project_path(params[:entry][:project_id])
		else
	        render :new
	    end
	end

	def destroy
		#perhaps a different route when deleting from entries index page? (link currently removed)
		entry = Entry.find(params[:id])
		entry.destroy
        flash[:success] = "Time entry successfully deleted."
		redirect_to project_path(entry.project.id)
	end

	private

	def entry_params
		params.require(:entry).permit(:date, :start_time, :end_time, :notes, :user_id, :project_id)
	end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :current_project, except: [:index, :create, :new, :status, :allprojects]

  def index
    @projects = Project.user_projects(current_user)
    respond_to do |f|
      f.html {render :index}
      f.json {render json: @projects}
    end
  end

  def new
    @project = Project.new
    render :new, layout: false
  end

  def create
    @project = Project.new(project_params)
    @owner = User.find(@project.owner)
    if @project.save  
      render :json => {:project => @project, :owner => @owner}, status: 201
    end
  end

  def show
    @project = Project.find(params[:id])
    @owner = User.find(@project.owner)
    @entries = @project.entries.desc_order
    respond_to do |f|
      f.html {render :show}
      # f.json {render :json => {:project => @project, :owner => @owner, :entries => @entries}}
      f.json {render json: @project}
    end
  end

  def update
    @project.attributes = (project_params)
    if @project.save
      flash[:success] = "Project successfully updated!"
      redirect_to @project
    else
      flash[:alert] = "Project name cannot be blank."
      redirect_to edit_project_path(@project)
    end
  end

  def destroy
    @project.destroy
    flash[:success] = "Project successfully deleted!"
    redirect_to user_projects_path(current_user)
  end

  def status
    @projects = Project.all.status(params[:status])
  end

  def allprojects
    @statuses = Project.new.statuses
  end

  private

  def current_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :deadline, :status, :owner)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if auth_hash
      @user = User.find_or_create_by(uid: auth_hash['uid']) do |u|
        u.name= auth_hash['info']['name']
        u.email= auth_hash['info']['email']
        u.password= SecureRandom.hex
        u.password_confirmation = u.password
      end
      session[:user_id] = @user.id
      redirect_to '/dashboard'
    else
      @user = User.find_by(email: params[:user][:email])
      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to '/dashboard'
      else
        flash[:alert] = "Please make sure your email and password are entered correctly."
        redirect_to '/login'
      end
    end
  end

  def destroy
    session.delete :user_id
    flash[:success] = "You have successfully logged out!"
    redirect_to '/'
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if current_user
      @user = current_user
      @entries = current_user.entries.latest 
    else
      redirect_to root_path
    end
  end

  def create
      @user = User.new(user_params)
      if @user.valid?
        @user.save
        session[:user_id] = @user.id
        redirect_to '/dashboard'
      else
        render :new 
      end
  end

  def show
    @user = User.find(params[:id])
  end

########trying to get image upload working from user show page
  def update 
    if current_user
      @user = current_user
      @user.image.attach(params[:image])
      @user.save
      redirect_to user_path(@user)
    else
      render root_path
    end
  end
########

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def home
		if current_user
			redirect_to dashboard_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/entries/_form.html.erb
<%= form_for entry do |f| %>
  <table id="table">
    <tr>
      <td>
        <%= f.label "Choose Project:" %>
      </td>
      <td>
        <%= f.collection_select :project_id, Project.all, :id, :name, :selected => @selected %>
      </td>
    </tr>

      <%= f.hidden_field :user_id, value: session[:user_id] %>

    <tr>
      <td>
      <%= f.label "Date:" %>
      </td>
      <td>
        <%= f.date_select :date %></br>
      </td>
    </tr>

      <td>
        <%= f.label "Start time:" %>
      </td>
      <td>
        <%= f.time_select :start_time, :minute_step => 15 %>
      </td>
    <tr>
      <td>
        <%= f.label "End time:" %>
      </td>
      <td>
        <%= f.time_select :end_time, :minute_step => 15 %>
      </td>
    </tr>
      <td>
        <%= f.label "Notes:" %>
      </td>
      <td>
        <%= f.text_field :notes %>
      </td>
  </table>

  <p><%= f.submit class: "btn btn-primary btn-sm" %></p>

<% end %>

app/views/entries/index.html.erb
<div id="username">
</div>

<!-- filter for entries
<p>
 <%#= form_tag(user_entries_path(current_user), method: "get") do %>
    <%#= select_tag "project", options_from_collection_for_select(@project, "id", "name"), prompt: "Filter by project:" %>
    <%#= submit_tag "Filter" %>
  <%# end %>
</p>

<hr>

 end filter -->


 <div id="entries-list">
</div>

<p>
	<%= link_to "+ Add entry", new_user_entry_path(current_user), class: "btn btn-primary btn-sm" %>
</p>

app/views/entries/index_old.html.erb
<h2>Time Entries: <%= current_user.name %></h2>

<hr>

<!-- filter for entries -->
<p>
 <%= form_tag(user_entries_path(current_user), method: "get") do %>
    <%= select_tag "project", options_from_collection_for_select(@project, "id", "name"), prompt: "Filter by project:" %>
    <%= submit_tag "Filter" %>
  <% end %>
</p>

 <!-- end filter -->

<hr>

<table>
	<tr>
		<th>Date</th>
		<th>Project</th>
		<th>Hours</th>
		<th>Notes</th>
	</tr>

	<% @entries.each do |entry| %>
		<tr>
			<td><%= entry.calc_date(entry.date) %></strong> </td>
			<td><strong><%= link_to entry.project.name, project_path(entry.project) %></strong></td>
			<td><%= entry.calc_time(entry.start_time) %> to <%= entry.calc_time(entry.end_time) %></td>
			<td><i><%= entry.notes %></i></td>
			<td><%#= link_to "delete entry", "/entries/#{entry.id}", method: :delete, class: "form_button" %></td>
		 </tr>
	<% end %>
	<tr>
		<td></td><td class="table_total"><strong>Total hours worked:</strong> 
		</td><td class="table_total"><strong><%= Entry.calc_hours(@entries) %></strong></td>
	</tr>
</table>

<p>
</p>

<p>
	<%= link_to "+ Add entry", new_user_entry_path(current_user), class: "btn btn-primary btn-sm" %>
</p>

app/views/entries/new.html.erb
<h2>Create a new time entry</h2>

<p><font color="red"><%= @entry.errors.full_messages.first if @entry.errors.any? %></font></p>

<%= render partial: "form", locals: {entry: @entry} %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">TimeTracker</a>
          </div>

    <ul class="nav navbar-nav">
      <li> <%= link_to "Dashboard", dashboard_path %></li>
      <li><%= link_to "Your Time Entries", entries_path %></li>
      <li><%= link_to "Your Projects", user_projects_path(current_user) %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "[ Your Profile ]", user_path(current_user) %></li>
      <li><%= link_to "[ Log Out ]", logout_path, method: :destroy %></li>
    </ul>

  </div>
</nav>

app/views/layouts/_welcomenav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">TimeTracker</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/login"> Login</a></li>
      <li><a href="/signup">Sign up</a></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeTracker App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>

  <body>

    <% if current_user %>
      <%= render "/layouts/navigation" %>
    <% else %>
      <%= render "/layouts/welcomenav" %>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger text-center"> <%= flash[:alert] %></div>
    <% end %>

    <% if flash[:success] %>
      <div class="alert alert-success text-center" id="success"> <%= flash[:success] %></div>
    <% end %>

    <!-- div added for JS functionality -->
    <div id="alert-js"></div>

    <div class="container" role="main">
      <div class="row">
        <div class="col-md-offset-1 col-md-10">
      <%= yield %>
        </div>
      </div>
    </div>

    <div class="container">
      <footer class="footer">
          <small><strong><% if current_user %>Logged in as: <%= current_user.name %> &nbsp; | &nbsp; <% end %>
          &copy; 2019 TimeTracker</strong></small>
        </footer>
    </div>

  </body>
</html>

app/views/projects/_form.html.erb
<hr>
<h3>Add New Project</h3>

<%= form_for @project do |f| %>

  <table>
    <tr>
      <td>
        <%= f.label "Project Owner:" %>
      </td>
      <td>
        <%= current_user.name %>
        <%= f.hidden_field :owner, value: current_user.id %>
        <%#= f.collection_select :owner, User.all, :id, :name, :selected => current_user.id %>
      </td>
    </tr>

      <td>
        <%= f.label "Project Name:" %>
      </td>
      <td>
        <%= f.text_field :name %>
      </td>

    <tr>
      <td>
        <%= f.label "Deadline:" %>
      </td>
      <td>
        <%= f.date_select :deadline %>
      </td>
    </tr>

      <td>
        <%= f.label "Status:" %>
      </td>
      <td>
        <%= f.select :status, @project.statuses %>
      </td>
  </table>

    <p><%= f.submit class: "btn btn-primary btn-sm" %></p>

<% end %>

app/views/projects/allprojects.html.erb
<h2>All Projects</h2>

<hr>

<!-- filter for project status -->

<table>
<tr><td>View stats on projects that are currently:</td><td>
	<%= form_tag(status_path, method: "get") do %>
    <%= select_tag "status", options_for_select(@statuses), prompt: "Choose status:" %>
    <%= submit_tag "View" %>
	  <% end %>
</td></tr>
</table>

 <!-- end filter -->

<hr>

<table>
	<tr>
		<th>Project Name</th>
		<th>Project Owner</th>
	</tr>
	
	  <% Project.all.each do |project| %>
	  	<tr><td><strong><%= link_to "#{project.name}", project_path(project) %></strong></td>
	  	<td><%= link_to Project.project_owner(project).name, user_path(Project.project_owner(project)) %></td></tr>
	  <% end %>
</table>

<hr>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>

<p><font color="red"><%= @project.errors.full_messages.first if @project.errors.any? %></font></p>

<%= render partial: "form", locals: {project: @project} %>

app/views/projects/index.html.erb
<h2>Your Projects</h2>

<hr>

<table id="projects-table">
	<tr>
		<th>Project Name</th>
		<th>Project Owner</th>
		<th>Current Status</th>
		<th>Total Hours</th>

	</tr>
	
	  <% @projects.each do |project| %>
	  	<tr><td><strong><%= link_to "#{project.name}", project_path(project) %></strong></td>
	  	<td><%= link_to Project.project_owner(project).name, user_path(Project.project_owner(project)) %></td>
	  	<td><%= project.status %></td>
	  	<td><%= Entry.calc_hours(project.entries.desc_order) %></td>
	  	</tr>
	  <% end %>
</table>



<hr>

<%#= link_to "+ Add project", new_user_project_path(@current_user), class: "btn btn-primary btn-sm" %>
<%= link_to "+ Add project", "#", class: "btn btn-primary btn-sm", id: "js-add-project" %>
<%= link_to "View all projects", all_projects_path, class: "btn btn-success btn-sm" %>

<div id="js-new-project-form"></div>

app/views/projects/new.html.erb
<%= render partial: "form"%>

app/views/projects/show.html.erb
<!-- this div contains JSON data for project -->
<div id="project-info"></div>

<hr>

<% if @owner.name == current_user.name %>
	<%= link_to 'Edit Project', edit_project_path(@project), class: "btn btn-primary btn-sm" %>
	<%= link_to "Delete Project", "/projects/#{@project.id}", method: :delete, data: {confirm: "NOTE: Deleting a project will delete all related time entries!"}, class: "btn btn-danger btn-sm" %>
<% end %>

<hr>

<h3>Project Activity:</h3>

<!-- this div contains JSON data for entries -->
<div id="entries-info"></div>



<% if @entries.empty? %>
	<p><i>No activity has been recorded for this project yet. Click below to add an entry:</i></p>
<% end %>


<p>
	<%= link_to "+ Add entry", new_project_entry_path(@project), class: "btn btn-primary btn-sm" %>
</p>

app/views/projects/show_old.html.erb
<h2>Project Name: <%= @project.name %></h2>

<hr>

<table>
	<tr><td><strong>Owner:</strong></td><td> <%= link_to @owner.name, user_path(@owner) %></td></tr>
	<tr><td><strong>Status:</strong></td><td> <%= @project.status %></td></tr>
	<tr><td><strong>Deadline:</strong></td><td> <%= @project.calc_date(@project.deadline) %></td></tr>

<% if @owner.name == current_user.name %>
	<td><%= link_to 'Edit Project', edit_project_path(@project), class: "btn btn-primary btn-sm" %></td>
	<td><%= link_to "Delete Project", "/projects/#{@project.id}", method: :delete, data: {confirm: "NOTE: Deleting a project will delete all related time entries!"}, class: "btn btn-danger btn-sm" %></td>
<% end %>
</table>

<hr>

<h3>Project Activity:</h3>


<% if @entries.empty? %>
	<p><i>No activity has been recorded for this project yet. Click below to add an entry:</i></p>
<% else %>

	<table>
		<tr>
			<th>Date</th>
			<th>Contributor</th>
			<th>Hours</th>
			<th>Notes</th>
		</tr>

		<% @entries.each do |entry| %>
			<tr>
				<td><%= entry.calc_date(entry.date) %></strong> </td>
				<td><%= link_to entry.user.name, user_path(entry.user) %></td>
				<td><%= entry.calc_time(entry.start_time) %> to <%= entry.calc_time(entry.end_time) %></td>
				<td><i><%= entry.notes %></i></td>
				<td><% if entry.user.name == current_user.name %> <%= link_to "delete entry", "/entries/#{entry.id}", method: :delete, class: "form_button" %><% end %></td>
			</tr>
		<% end %>
		<tr>
			<td></td><td class="table_total"><strong>Total hours:</strong> 
			</td><td class="table_total"><strong><%= Entry.calc_hours(@entries) %></strong></td>
		</tr>
	</table>

	<p>
	</p>

<% end %>

<p>
	<%= link_to "+ Add entry", new_project_entry_path(@project), class: "btn btn-primary btn-sm" %>
</p>

app/views/projects/status.html.erb
<h2>Filter by Status</h2>

<hr>

<% if @projects.empty? %>

	There are currently no projects with that status.

<% else %>

	<table>
		<tr>
			<th>Project Name</th>
			<th>Project Owner</th>
			<th>Current Status</th>
			<th>Total Hours</th>

		</tr>
		
		  <% @projects.each do |project| %>
		  	<tr><td><strong><%= link_to "#{project.name}", project_path(project) %></strong></td>
		  	<td><%= link_to Project.project_owner(project).name, user_path(Project.project_owner(project)) %></td>
		  	<td><%= project.status %></td>
		  	<td><%= Entry.calc_hours(project.entries.desc_order) %></td>
		  	</tr>
		  <% end %>
	</table>

<% end %>

<hr>

<%= link_to "Back to all projects", all_projects_path, class: "btn btn-success btn-sm" %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <div class="form-group">
        <%= form_for user do |f| %>
        <%= f.label :image %>
          <%= f.file_field :image %><br>

              <%= f.submit class: 'btn btn-primary btn-block' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h2>Welcome <%= @user.name %>!</h2>

<hr>

<div class="row row-eq-height">
	<div class="col-md-offset-0 col-md-6">
		<h3>Recent activity:</h3>

		<% if Entry.all.empty? %>
			There are no recent entries.

		<% else %>
			<ul>
				<% Entry.all.latest.each do |entry| %>
				<li>
					<% hour = Entry.calc_hours_entry(entry) %>
					<% if hour > 1 %>
					<%= link_to entry.user.name, user_path(entry.user) %> worked on <%= link_to entry.project.name, project_path(entry.project) %> for <strong><%= hour%> hours</strong>
					<% else %>
					<%= link_to entry.user.name, user_path(entry.user) %> worked on <%= link_to entry.project.name, project_path(entry.project) %> for <strong><%= hour %> hour</strong>
					<% end %>
				</li>
				<% end %>
			</ul>

		<% end %>

		<div class="bottom-div">
			<%= link_to "+ Add entry", new_user_entry_path(current_user), class: "btn btn-success btn-sm btn-block" %>
		</div>
	</div>

	<div class="col-md-offset-0 col-md-6">
		<h3>Your Projects:</h3>

		<% if Project.user_projects(current_user).empty? %>
			
			You currently do not have any projects.

		<% else %>
			<ul>
				<% Project.user_projects(current_user).each do |project| %>
				<li><%= link_to project.name, project_path(project) %> </li>
				<% end %>
			</ul>
		<div class="bottom-div">
			<%= link_to "View All", all_projects_path, class: "btn btn-success btn-sm btn-block" %>
		</div>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<div class="signup_header">
  <h1>Sign Up</h1>
</div>

<div class="col-md-offset-4 col-md-5">

  <p>
  <font color="red">
  <ul>
  <% if @user && @user.errors.any? %>
    <% @user.errors.full_messages.each do |error| %>
      <li><%= error%></li>
    <% end %>
  <% end %>
  </ul>
  </font>
</p>

  <%= form_for :user, url: '/signup' do |f| %>

  <table>
    <tr>
      <td>
        <%= f.label "Your Name:" %>
      </td>
      <td>
        <%= f.text_field :name %>
      </td>
    </tr>

      <td>
        <%= f.label "Your Email:" %>
      </td>
      <td>
        <%= f.text_field :email %>
      </td>

    <tr>
      <td>
        <%= f.label "Password:" %>
      </td>
      <td>
        <%= f.password_field :password %>
      </td>
    </tr>

      <td>
        <%= f.label "Password Confirmation:" %>
      </td>
      <td>
        <%= f.password_field :password_confirmation %>
      </td>
  </table>

    <p><%= f.submit "Signup", class: "btn btn-primary btn-sm" %></p>

  <% end %>

  <%= link_to "Signup with Facebook", "/auth/facebook", class: "btn btn-success btn-sm" %>

</div>

app/views/users/show.html.erb
<h2>Profile: <%= @user.name %></h2>


<p>
	<%= image_tag "headshot.png", alt: "Headshot", style: 'height:20%; width: 20%;' %>
</p>

<p>
	<strong>Bio:</strong></br>
	This is the show page for users 
	This is the show page for users 
	This is the show page for users 
	This is the show page for users 
	This is the show page for users 
	This is the show page for users 
	This is the show page for users 
	This is the show page for users 
	This is the show page for users 
	This is the show page for users 
	This is the show page for users 
	This is the show page for users 
</p>

<strong>Current Location:</strong> Berlin, Germany




<%#= image_tag(@user.image, style:'width:100%') %>
<%#= render partial: "form", locals: {user: @user} %>

app/views/welcome/home.html.erb
<div class="signup_header">
	<h1>Let's go!</h1>
	<h3>Be more productive with the TimeTracker app.</h3>

	<%= image_tag "welcome.png", alt: "Welcome Image" %>
</div>